=== Lutscherdieb/Dungeon_CardGenerator/schemas/room.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Room Card",
  "type": "object",
  "required": ["Name", "Mana", "Cards", "Defence", "Treasure"],
  "properties": {
    "Type": { "const": "Room" },
    "Name": { "type": "string", "minLength": 1 },
    "Rules": { "type": "string" },
    "Mana": { "type": "integer" },
    "Cards": { "type": "integer" },
    "Food":       { "type": "integer" },
    "Defence": { "type": "integer" },
    "Treasure": { "type": "integer" },
    "Subtype": { "type": "string", "enum": ["Hearth","Basic"] },
    "Roads": {
      "type": "array",
      "items": { "type": "string" }
    },
    "Slots": {
  "type": "array",
  "items": {
    "type": "object",
    "patternProperties": {
      "^[0-9]+$": {
        "type": "array",
        "items": {
          "type": "array",
          "prefixItems": [
            { "type": "string", "enum": ["Demon", "Undead", "Magic", "Wild", "All"] },
            { "type": "integer" }
          ],
          "minItems": 2,
          "maxItems": 2
        }
      }
    },
    "additionalProperties": false
  }
}
,
    "Background": { "type": "string" }
  },
  "additionalProperties": true
}

=== Lutscherdieb/Dungeon_CardGenerator/data/Mixed/Skull Pit.json
{
    "Type":"Room",
    "Subtype": "Basic",
    "Name":"Skull Pit",
    "Rules":"Can store up to 2 [Mana]",
    "Mana":2,
    "Cards":1,
    "Defence":0,
    "Treasure":0,
    "Roads":[],
    "Slots":[
        {"1":[]},
        {"2":[]},
        {"3":[]}
    ],
    "Background": "./backgrounds/Skull_Pit.png"
}

=== Lutscherdieb/Dungeon_CardGenerator/data/Mixed/Blood_Altar.json
{
    "Type":"Room",
    "Subtype": "Basic",
    "Name":"Blood Altar",
    "Rules":"Whenever [All] or [Hero] dies in this room, gain 1 [Cards]",
    "Mana":0,
    "Cards":2,
    "Defence":2,
    "Treasure":0,
    "Roads":["N","S"],
    "Slots":[
        {"1":[ ["All", 0],["All",0]]},
        {"2":[["Demon", 0]]},
        {"3":[]}
    ],
    "Background": "./backgrounds/Blood_Altar.png"
}

=== Lutscherdieb/Dungeon_CardGenerator/data/Mixed/Necromantic_Hearth.json
{
    "Type": "Room",
    "Subtype": "Hearth",
    "Name": "Necromantic Hearth",
    "Rules": "",
    "Mana": 0,
    "Cards": 0,
    "Defence": 2,
    "Treasure": 3,
    "Roads": [
        "S"
    ],
    "Slots": [
        {
            "1": [
                [
                    "Undead",
                    0
                ],
                [
                    "Undead",
                    0
                ]
            ]
        },
        {
            "2": [
                [
                    "All",
                    0
                ]
            ]
        },
        {
            "3": []
        }
    ],
    "Background": "./backgrounds/Necromantic_Hearth.png"
}

=== Lutscherdieb/Dungeon_CardGenerator/data/Mixed/Liquid Hearth.json
{
  "Type": "Room",
  "Subtype": "Hearth",
  "Name": "Liquid Hearth",
  "Rules": "",
  "Mana": 0,
  "Cards": 0,
  "Defence": 1,
  "Treasure": 2,
  "Roads": ["N","E","S","W"],
  "Slots": [
        { "1": [ ["Magic", 0], ["Magic", 0] ] },
        { "2": [["All",0]] },
        { "3": [] }
        ],
  "Background": "./backgrounds/Liquid_Hearth.png"
}

=== Lutscherdieb/Dungeon_CardGenerator/data/Mixed/Sacred Hain.json
{
    "Type":"Room",
    "Subtype": "Basic",
    "Name":"Sacred Hain",
    "Rules":"If a [Wild] with Level 1 would die, return it to your Domain instead",
    "Mana":3,
    "Cards":1,
    "Defence":1,
    "Treasure":1,
    "Roads":["E","W"],
    "Slots":[
        {"1":[ ["Wild", 2], ["Wild", 2]]},
        {"2":[["All",0]]},
        {"3":[]}
    ],
    "Background": "./backgrounds/Sacred_Hain.png"
}

=== Lutscherdieb/Dungeon_CardGenerator/outputs/api/tmp_json/3_Acid_Chamber.json
{
  "Type": "Room",
  "Subtype": "Basic",
  "Name": "Acid Chamber",
  "Mana": 0,
  "Cards": 2,
  "Food": 0,
  "Defence": 1,
  "Treasure": 3,
  "Roads": [
    "N",
    "S"
  ],
  "Slots": [
    {
      "1": [
        [
          "All",
          0
        ]
      ]
    },
    {
      "2": [
        [
          "Magic",
          0
        ],
        [
          "Demon",
          0
        ]
      ]
    },
    {
      "3": []
    }
  ],
  "Rules": "",
  "Background": "./backgrounds/Acid_Chamber.png"
}

=== Lutscherdieb/Dungeon_CardGenerator/data/Mixed/Snake Pit.json
{
    "Type":"Room",
    "Subtype": "Basic",
    "Name":"Snake Pit",
    "Rules":"When a hero enters this Room, it is dealt 1 damage",
    "Mana":0,
    "Cards":1,
    "Defence":0,
    "Treasure":1,
    "Roads":["N","E","S"],
    "Slots":[
        {"1":[["Undead",0]]},
        {"2":[]},
        {"3":[]}
    ],
    "Background": "./backgrounds/Snake_Pit.png"
}

=== Lutscherdieb/Dungeon_CardGenerator/data/Mixed/Shark_Tank.json
{
    "Type": "Room",
    "Subtype": "Basic",
    "Name": "Shark Tank",
    "Rules": "[Wild] / [Magic],[Food]: Deal 3 damage to any one hero in this room",
    "Mana": 1,
    "Cards": 1,
    "Defence": -1,
    "Treasure": 1,
    "Roads": [
        "N",
        "E",
        "W"
    ],
    "Slots": [
        {
            "1": [
                [
                    "Wild",
                    0
                ],
                [
                    "Wild",
                    0
                ]
            ]
        },
        {
            "2": [
                [
                    "Magic",
                    0
                ],
                [
                    "Magic",
                    0
                ]
            ]
        },
        {
            "3": []
        }
    ],
    "Background": "./backgrounds/Shark_Tank.png"
}
